version: 2
jobs:
  py3test:
    working_directory: ~/pymatgen-db
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:0.0.2
        environment:
          PMG_MAPI_ENDPOINT: https://zola.lbl.gov/rest/v2
    parallelism: 4
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            # conda install --quiet --yes numpy scipy matplotlib sympy cython
            conda upgrade --quiet --all
            mkdir coverage_reports
            pip install --upgrade pip
            pip install --upgrade numpy
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt
            rm -r coverage_reports
      - run:
          command: |
            # Add executables and path.
            for EXEPATH in `pwd`/cmd_line/*/Linux_64bit; do export PATH=$PATH:$EXEPATH; done
            export PATH=$HOME/miniconda3/bin:$PATH
            export MPLBACKEND=Agg
            pip install --quiet -e .
            nosetests --config=nose.cfg --cover-html --cover-html-dir=coverage_reports
            # Command line tests
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
